services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: lanotte_app

    ports:
      - "8080:80"

    volumes:
      - ./:/var/www/html

    depends_on:
      - banco

  banco:
    image: mariadb:10.11

    container_name: lanotte_banco

    restart: always

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: lanotte
      MARIADB_USER: lanotte
      MARIADB_PASSWORD: lanotte123

    ports:
      - "3307:3306"

    volumes:
      - banco_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin:5.2-apache

    container_name: lanotte_pma

    restart: always

    ports:
      - "8081:80"

    environment:
      PMA_HOST: banco
      PMA_PORT: 3306

    depends_on:
      - banco

volumes:
  banco_data: