services:
    php:
        build:
            context: .
            dockerfile: docker/Dockerfile

        container_name: lanotte_php
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql

        networks:
            - rede_aulaLogin

    mysql:
        image: mysql:8.0

        container_name: lanotte_mysql

        environment:
            MYSQL_ROOT_PASSWORD: senha_root_123
            MYSQL_DATABASE: lanotte
            MYSQL_USER: lanotte_user
            MYSQL_PASSWORD: lanotte123

        volumes:
            - dados_mysql:/var/lib/mysql

            - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

        ports:
            - "3306:3306"

        networks:
            - rede_aulaLogin

    phpmyadmin:
        image: phpmyadmin:latest

        container_name: lanotte_phpmyadmin

        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: senha_root_123

        ports:
            # Acesse o phpMyAdmin em: http://localhost:8081
            - "8081:80"

        depends_on:
            - mysql

        networks:
            - rede_aulaLogin

volumes:
    dados_mysql:

networks:
    rede_aulaLogin:
        driver: bridge